name: Sonar Scan
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v1
      - name: Install conan && conan package tools
        run: |
          python -m pip install --upgrade pip
          pip install conan
          pip install conan_package_tools
      - uses: actions/checkout@v1
      - name: Prepare Sonar
        run: |
          wget https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
          unzip build-wrapper-linux-x86.zip
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.4.0.2170-linux.zip
          unzip sonar-scanner-cli-4.4.0.2170-linux.zip
          sudo apt-get update && sudo apt-get install -y gcovr
      - name: conan
        run: |
          conan remote add inexorgame "https://api.bintray.com/conan/inexorgame/inexor-conan"
          conan install . -s compiler.libcxx=libstdc++11 --build missing
      - name: cmake
        run: |
          cmake . -DCMAKE_TOOLCHAIN_FILE=conan_paths.cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="--coverage"
      - name: Build
        run: ./build-wrapper-linux-x86/build-wrapper-linux-x86-64 --out-dir bw_output cmake --build . -j4
      - name: Test
        run: |
          ctest --output-on-failure
          gcovr . --sonarqube test-coverage.xml
      - name: SonarCloud Scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./sonar-scanner-4.4.0.2170-linux/bin/sonar-scanner -Dsonar.host.url=https://sonarcloud.io
